app:
    host: http://balogotthon.ddns.net
server:
    port: 8112
spring:
    data:
        mongodb:
            database: agile-tool
        rest:
            base-path: /api
    social:
        facebook:
            appId: 1387159251342491
            appSecret: 8cce14dc94e1dc728de8e3bc53f68318